title: Elina Jussila
logo: /assets/placeholder.jpg 
description: Elina Jussila
#show_downloads: true

author:
  # Biographic information
  name             : "Ellu"
  bio              : "Short biography for the left-hand sidebar"
  employer         : "Tampere University"
  email            : "elina.jussila@tuni.fi" 

  
theme: jekyll-theme-minimal

remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

#ohjeet: https://www.youtube.com/watch?v=D9CLhQdLp8w&t=107s
