#title: Elina Jussila
logo: /assets/placeholder.jpg 
description: *Elina Jussila* 
Tampere University
elina.jussila@tuni.fi
#show_downloads: true
theme: jekyll-theme-minimal

#ohjeet: https://www.youtube.com/watch?v=D9CLhQdLp8w&t=107s
